version: "3.1"

services:
  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8080:8080"
    links:
      - db:db

  db:
    image: mysql:5.7
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: yann
    volumes:
      - ./data:/var/lib/mysql
  
  wordpress:
    image: wordpress
    container_name: wordpress
    ports:
      - "8001:80"
    volumes:
      - ./src:/var/www/html